name: pcsx2-emulator
base: core24
version: 2.6.1
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: PlayStation 2 emulator
description: |
  PCSX2 is a free and open-source PlayStation 2 (PS2) emulator. Its purpose is to emulate the PS2's hardware, using a combination of MIPS CPU Interpreters, Recompilers, and a Virtual Machine which manages hardware states and PS2 system memory. This allows you to play PS2 games on your PC, with many additional features and benefits.

  PlayStation 2 and PS2 are registered trademarks of Sony Interactive Entertainment. This application is not affiliated in any way with Sony Interactive Entertainment.
grade: stable
confinement: strict
icon: AppIconLarge.png

apps:
  pcsx2-emulator:
    command-chain: [snap/command-chain/unset-qt_qpa_platform]
    command: usr/bin/pcsx2-qt
    desktop: usr/share/applications/PCSX2.desktop
    common-id: net.pcsx2.PCSX2
    environment:
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]
    plugs:
      - screen-inhibit-control
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - udisks2

plugs:
  shared-memory:
    private: true
  lxqt-support-core24:
    content: lxqt-support-core24
    interface: content
    target: $SNAP/lxqt-support-core24
    default-provider: lxqt-support-core24

layout:
  /usr/share/color-schemes:
    symlink: $SNAP/lxqt-support-core24/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support-core24/usr/share/Kvantum

package-repositories:
  - type: apt
    url: https://ppa.launchpadcontent.net/pcsx2-team/pcsx2-daily/ubuntu
    suites: [noble]
    components: [main]
    architectures: [amd64]
    key-id: D7B449CFE17E659E5A12EE8EDD6EEEA2BD747717

parts:
  pcsx2-app:
    plugin: dump
    source: http://ppa.launchpad.net/pcsx2-team/pcsx2-daily/ubuntu/pool/main/p/pcsx2-stable/pcsx2-stable_$SNAPCRAFT_PROJECT_VERSION~ubuntu24.04.1_amd64.deb
    stage-packages:
      - pcsx2-patches
    override-build: |
      craftctl default
      sed -i 's|Name=PCSX2|Name=PCSX2 [Kyu]|' $CRAFT_PART_INSTALL/usr/share/applications/PCSX2.desktop
    prime:
      - usr/bin/pcsx2-qt
      - usr/share/applications/PCSX2.desktop
      - usr/share/icons/hicolor/256x256/apps/PCSX2.png
      - usr/share/lintian/overrides/pcsx2-stable
      - usr/share/menu/pcsx2-stable
      - usr/share/PCSX2/resources
      - usr/share/PCSX2/translations

  dependencies:
    after: [pcsx2-app]
    plugin: nil
    stage-packages:
      - libpcap0.8t64
      - libshaderc1
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/

  command-chain:
    after: [dependencies]
    plugin: dump
    source: ./command-chain/
    organize:
      unset-qt_qpa_platform: snap/command-chain/unset-qt_qpa_platform
